---
title: "Blog assignment"
---

```{r, include=FALSE}
knitr::opts_chunk$set(cache = TRUE)
```

## Format, due date

- Create a blog at <http://sites.psu.edu> or add pages to an existing blog; make at least three posts.
- Worth 15 points in total (5 points/post)
- Due dates/times
    - Post 1: **Thursday, October 7, 2021, 5:00 pm**
    - Post 2: **Thursday, November 4, 2021, 5:00 pm**
    - Post 3:  **Tuesday, November 30, 2021 at 5:00 pm**
- Submit by sending email with link (URL) to the TA, cc the instructor.
- Please indicate in your email whether you wish to have the link to your blog added to the course web site.

## Assignment

Create a blog at <http://sites.psu.edu> or add to an existing blog you have created.

Write at least three posts between now and **Tuesday, November 30, 2021 at 5:00 pm** that discuss different issues on any topic related to the biology of behavior. Your posts should be 1-3 paragraphs in length, or approximately 1-1.5 pp double-spaced. Blog post #1 is due **Thursday, October 7**; Blog post #2 is due **Thursday, November 4**. Blog post #3 is due **Tuesday, November 30.**

You may choose to comment on articles from the popular or scientific press. You can find appropriate articles in general interest magazines such as Time, The Economist, in a newspaper such as *The New York Times*, in general science publications such as *Scientific American*, *The American Scientist*, *Science News*, or *Discover*, or scientific journals such as *Science*, *Nature*, *Current Directions in Psychological Science*, etc. You may choose to discuss a topic we covered in class, perhaps how it might relate to you or to someone you know but you should incorporate the scientific literature.

Summarize and discuss the main points of the articles as follows:

1. Describe the main purposes and findings of the research reported on in the articles. Remember the strategy that good reporters use: Who did what to whom, when and how did they do it, and why?
2. Discuss what is known about the neural mechanisms underlying the behavior in question, what are the strengths and weaknesses of the approach to studying the biology of behavior undertaken by the investigators you are writing about, and how the current results expand or alter our knowledge about the topic.
3. Discuss why the new discovery or issue covered in the article is important and interesting, and what questions about the topic remain to be answered. In other words, why should a general audience care about this topic, and what do we still need to know?

If your non-textbook references are unavailable online, submit printed paper copies. NOTE: Remember to include proper APA in-text citations and also include full references for your sources at the end of each post. 

THE TA OR I WILL BE HAPPY TO DISCUSS POSSIBLE ARTICLES AND TOPICS WITH YOU.

Be mindful of personal privacy. You should not reveal sensitive or personal information about yourself or another person in any way that could cause harm or embarrassment.

## How to submit

Send an email to Dr. Gilmore and the TA. Include the URL (web link) to your blog in the message.

## Sources

You may use your textbook or other reference materials as resources. When mentioning a finding that appears in your textbook or another source, please cite the source using the APA Publication Manual format — e.g. (Gilmore & Cohen, 2003). If you use sources other than your textbook, provide a full bibliographic reference at the end of your paper. Wherever possible, link to articles or figures in your post so that others can follow what you've found.
